version: '3.8'  # Specify Docker Compose version

services:
  postgresql:
    image: postgres
    restart: always  # Restart the container if it stops
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
    networks:
      - pg-network
    secrets:
      - POSTGRES_PASSWORD


  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "fosternilsson99@gmail.com"
    networks:
      - pg-network
    secrets:
      - PGADMIN_DEFAULT_PASSWORD  

  flask_app:
    build: .  
    environment:

    volumes:
      - ./templates/index.html:/app/templates/index.html
      - ./static/:/app/static/ 
    networks:
      - pg-network
      - cloudflare-nginx
    secrets:
      - DB_HOST
      - DB_USER
      - DB_PASSWORD
      - DB_NAME

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./cloudflare_origin_cert.pem:/etc/ssl/certs/cloudflare_origin_cert.pem
      - ./cloudflare_origin_key.pem:/etc/ssl/private/cloudflare_origin_key.pem
    networks:
      - cloudflare-nginx
  
  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token-file /run/secrets/CLOUDFLARE_TOKEN --url http://my-nginx:443
    networks:
      - cloudflare-nginx
    secrets:
      - source: CLOUDFLARE_TOKEN
        target: /run/secrets/CLOUDFLARE_TOKEN  
        mode: 0400 

networks:
  pg-network:
  cloudflare-nginx:

secrets:
  POSTGRES_PASSWORD:
    external: true
  PGADMIN_DEFAULT_PASSWORD:
    external: true
  DB_USER:
    external: true
  DB_PASSWORD:
    external: true
  DB_NAME:
    external: true  
  CLOUDFLARE_TOKEN:
    file: ./cloudflare_token.txt 
